/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author u4rs9jsg
 */
public class Extract extends javax.swing.JFrame {

    /**
     * Creates new form Extract
     */
    public Extract() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        buttonGroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        watershed_list = new javax.swing.JList();
        label = new javax.swing.JLabel();
        dsspath = new javax.swing.JTextField();
        select_button = new javax.swing.JButton();
        execute_button = new javax.swing.JButton();
        check_box = new javax.swing.JCheckBox();
        apart = new javax.swing.JTextField();
        save_button = new javax.swing.JButton();
        name_radio_button = new javax.swing.JRadioButton();
        label1 = new javax.swing.JLabel();
        site_num_radio_button = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Extract Time Series Configuration");
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(10, 10));
        setLocationByPlatform(true);
        setName("WaterExtractUI"); // NOI18N

        watershed_list.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Watersheds", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        watershed_list.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        watershed_list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        watershed_list.setToolTipText("List of watersheds");
        jScrollPane1.setViewportView(watershed_list);

        label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label.setText("DSS File Downloads");

        dsspath.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dsspath.setToolTipText("FQPN to output file (.dss)");

        select_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        select_button.setText("...");
        select_button.setToolTipText("Select File...");
        select_button.setActionCommand("");

        execute_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        execute_button.setText("Save and Execute Configuration");
        execute_button.setToolTipText("Save and Execute Configuration");
        execute_button.setActionCommand("");
        execute_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        check_box.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        check_box.setText("DSS A part");
        check_box.setToolTipText("DSS A part override");

        apart.setEditable(false);
        apart.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        apart.setToolTipText("DSS A part override");

        save_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        save_button.setText("Save Configuration");
        save_button.setToolTipText("Save Configuration");
        save_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        buttonGroup.add(name_radio_button);
        name_radio_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name_radio_button.setSelected(true);
        name_radio_button.setLabel("name");

        label1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label1.setText("DSS B part");

        buttonGroup.add(site_num_radio_button);
        site_num_radio_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        site_num_radio_button.setText("Site Number");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 92, Short.MAX_VALUE)
                        .addComponent(execute_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(save_button))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(dsspath)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(select_button))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label1)
                                .addGap(27, 27, 27)
                                .addComponent(name_radio_button)
                                .addGap(43, 43, 43)
                                .addComponent(site_num_radio_button)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(check_box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apart)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(check_box)
                    .addComponent(apart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1)
                    .addComponent(name_radio_button)
                    .addComponent(site_num_radio_button))
                .addGap(18, 18, 18)
                .addComponent(label)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dsspath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(select_button))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(execute_button)
                    .addComponent(save_button))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Extract.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Extract.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Extract.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Extract.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Extract().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apart;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JCheckBox check_box;
    private javax.swing.JTextField dsspath;
    private javax.swing.JButton execute_button;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label1;
    private javax.swing.JRadioButton name_radio_button;
    private javax.swing.JButton save_button;
    private javax.swing.JButton select_button;
    private javax.swing.JRadioButton site_num_radio_button;
    private javax.swing.JList watershed_list;
    // End of variables declaration//GEN-END:variables
}
